### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by pzk-creator** [VIP-Share/Baidu-XunleiVIP#3]
没法用是怎么回事啊

**Comment by VIP-Share** [comment]
微博登录啊。账号都是有时效性的。
---原始邮件---
发件人:"风中的飞鸟"<notifications@github.com>
发送时间:2020年4月24日 星期五 下午6:4
收件人:"VIP-Share/Baidu-XunleiVIP"<Baidu-XunleiVIP@noreply.github.com>
抄送:"Subscribed"<subscribed@noreply.github.com>
主题:[VIP-Share/Baidu-XunleiVIP] 疑问 (#3)



没法用是怎么回事啊

&mdash;
